### ISSUE TITLE
Crash when destroying garage door

### ISSUE THREAD

**Issue by Nerodon** [sketchmacaw/MacawsDoors#1]
This exception occurs when destroying garage doors. This crashes the server. 
On Version mcw-doors-1.0.8forge-mc1.16.5.jar

java.lang.NoSuchMethodError: com.mcwdoors.kikoz.objects.GarageDoor.addDestroyEffects(Lnet/minecraft/block/BlockState;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/client/particle/ParticleManager;)Z
	at com.mcwdoors.kikoz.objects.GarageDoor.func_176208_a(GarageDoor.java:188) ~[mcwdoors:1.0]
	at net.minecraftforge.common.extensions.IForgeBlock.removedByPlayer(IForgeBlock.java:199) ~[forge:?]
	at net.minecraftforge.common.extensions.IForgeBlockState.removedByPlayer(IForgeBlockState.java:143) ~[forge:?]
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:271) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:254) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:190) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?]
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by sketchmacaw** [comment]
Fixed in the latest [v1.0.8b / mc1.16.5 - Forge](https://www.curseforge.com/minecraft/mc-mods/macaws-doors/files/4435414)
